travelbuddy/destinations/urls.py
from django.urls import include, path
from .views import UpdateDestinationView
from .views import (
    HomeView,
    AddDestinationFormView,
    DestinationDetailSlugView,
)

urlpatterns = [
    path('dashboard', HomeView.as_view(), name='home'),
    path('destination/add', AddDestinationFormView.as_view(), name='add_trip'),
    # path('destination/update/', UpdateDestinationView.as_view(), name='destination_update'),
    path('destination/update/', UpdateDestinationView, name='destination_update'),
    path('destination/<slug:slug>/', DestinationDetailSlugView.as_view(), name='detail'),
]

travelbuddy/travel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', include(('apps.accounts.urls', 'account'), namespace='account')),  # Removed the 'r'^' as it's not required
    path('travel/', include(('apps.destinations.urls', 'travel'), namespace='travel')),  # Removed the 'r'^' as it's not required
    path('logout/', LogoutView.as_view(), name='logout'),  # Removed the 'r'^' as it's not required
    path('admin/', admin.site.urls),  # Removed the 'r'^' as it's not required
]

if settings.DEBUG:  # If it is in debug mode
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # Concatenate the static URLs correctly
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Concatenate the static URLs correctly

travelbuddy/templates/partials/navbar.html
<!-- Navbar Section -->
{% load static %}
{% url 'home' as home_url %}
{% url 'travel:home' as home_url %}
{% url 'travel:add_trip' as add_trip_url %}
{% url 'logout' as logout_url %}

<!-- navbar section -->
<nav class="navbar navbar-expand-sm navbar-dark rounded">
    <div class="container">
        <a class="navbar-brand d-none d-md-inline" href="{{ home_url }}">
            <img src="{% static 'img/airplane_logo.png'%}" alt="airplane logo">
        </a>
        <h3 class="">Welcome, {{ user.username }}</h3>
        <!-- Hamburger button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item mr-3">
                    <a class="nav-link text-dark font-weight-bold btn btn-info" href="{{ add_trip_url }}">Add Trip</a>
                </li>

                <li class="nav-item ">
                    <a class="nav-link font-weight-bold btn btn-danger" href="{{ logout_url }}">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>