travelbuddy/destinations/urls.py
from django.urls import include, path
from .views import UpdateDestinationView
from .views import (
    HomeView,
    AddDestinationFormView,
    DestinationDetailSlugView,
)

urlpatterns = [
    path('dashboard', HomeView.as_view(), name='home'),
    path('destination/add', AddDestinationFormView.as_view(), name='add_trip'),
    # path('destination/update/', UpdateDestinationView.as_view(), name='destination_update'),
    path('destination/update/', UpdateDestinationView, name='destination_update'),
    path('destination/<slug:slug>/', DestinationDetailSlugView.as_view(), name='detail'),
]

travelbuddy/travel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', include(('apps.accounts.urls', 'account'), namespace='account')),  # Removed the 'r'^' as it's not required
    path('travel/', include(('apps.destinations.urls', 'travel'), namespace='travel')),  # Removed the 'r'^' as it's not required
    path('logout/', LogoutView.as_view(), name='logout'),  # Removed the 'r'^' as it's not required
    path('admin/', admin.site.urls),  # Removed the 'r'^' as it's not required
]

if settings.DEBUG:  # If it is in debug mode
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # Concatenate the static URLs correctly
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Concatenate the static URLs correctly

travelbuddy/destinations/models.py
from datetime import datetime
from django.db.models import BigAutoField
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.urls import reverse

from .signals import destination_pre_save_receiver
from .custom_queries import DestinationQuerySet
User = get_user_model()
now = str(datetime.now())


# implement adding images later
class DestinationManager(models.Manager):
    def get_queryset(self):
        return DestinationQuerySet(self.model, using=self._db)

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None

    def completed(self):  # Product.objects.featured()
        return self.get_queryset().completed()

    def update(self, request):  # adds or removes the authenticated user
        pass
    # def search(self, query):
    #     return self.get_queryset().active().search(query)
    def update_rating(self, destination_id, new_rating):
        destination = self.get_by_id(destination_id)
        if destination:
            destination.rating = new_rating
            destination.save()
            return destination

    def new(self, form, user=None):
        user_obj = user.id
        # created = False
        # obj = None
        errors = []
        if len(form.cleaned_data['description']) < 5:
            state = ' Description must be at least 5 characters'
            errors.append(state)
            form.add_error('description', state)
        if not form.cleaned_data['start_date']:
            state = ' Please select a Departure date'
            errors.append(state)
            form.add_error('description', state)
        if not form.cleaned_data['end_date']:
            errors.append('End date is required')

        if not errors:
            # errors=None
            # created = True
            obj = Destination.objects.create(location=form.cleaned_data['location'], description=form.cleaned_data['description'], planner=user, start_date=form.cleaned_data['start_date'], end_date=form.cleaned_data['end_date'])
            obj.users_on_trip.add(user_obj) # find a way of using the user model here instead --idk--?
            return (obj)
        return None


class Destination(models.Model):
    id = BigAutoField(primary_key=True)
    slug = models.SlugField(blank=True, unique=True)
    location = models.CharField(max_length=255)
    description = models.TextField()
    start_date = models.DateField(auto_now=False)
    end_date = models.DateField(auto_now=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)


    def get_absolute_url(self):
        return reverse('travel:detail', args=[str(self.slug)])

    def __str__(self):
        return str(self.location)

    objects = DestinationManager()


pre_save.connect(destination_pre_save_receiver, sender=Destination)

travelbuddy/destinations/forms.py
from django import forms
from django.contrib.auth import get_user_model
import datetime

now = datetime.datetime.now().replace(tzinfo=None)

class TripForm(forms.Form):
    name = forms.CharField(label="Trip Name", widget=forms.TextInput(
        attrs={"class": "form-control", 'id': 'form_name', "placeholder": "Give your trip a name", }))
    location = forms.CharField(label="Destination", widget=forms.TextInput(
        attrs={"class": "form-control", 'id': 'form_location', "placeholder": "Where are you traveling to?", }))
    description = forms.CharField(label="Description", widget=forms.Textarea(
        attrs={'class': 'form-control', 'id': 'form_description', 'rows': '3'}))
    start_date = forms.DateTimeField(label='Start Date', widget=forms.DateTimeInput(
        attrs={'type': 'date', 'class': 'form-control', 'id': 'form_start_date'}))
    end_date = forms.DateTimeField(label="End Date", widget=forms.DateInput(
        attrs={'type': 'date', "class": "form-control", 'id': 'form_end_date'}))
    rating = forms.IntegerField(label="Rating", widget=forms.NumberInput(
        attrs={'class': 'form-control', 'id': 'form_rating', 'min': '0', 'max': '5'}))  # Add the rating field

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        location = cleaned_data.get('location')
        description = cleaned_data.get('description')
        start_date = cleaned_data.get('start_date').replace(tzinfo=None)
        end_date = cleaned_data.get('end_date').replace(tzinfo=None)
        rating = cleaned_data.get('rating')  # Retrieve the rating field

        if not name:
            msg = 'Please provide a name for your trip'
            self.add_error('name', msg)
        if not location:
            msg = 'Please provide a location'
            self.add_error('location', msg)
        if not description:
            msg = 'No description was provided'
            self.add_error('description', msg)
        if start_date < now:
            msg = 'Start date must be in the future'
            self.add_error('start_date', msg)
        if end_date < now:
            msg = 'End date must be in the future'
            self.add_error('end_date', msg)
        if end_date < start_date:
            msg = 'End date must be after start date'
            self.add_error('end_date', msg)

        # Add validation for the rating field if needed

        return cleaned_data

travelbuddy/destinations/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import HttpResponse, redirect, render
from django.http import JsonResponse
from django.views.generic import TemplateView, DetailView
from .forms import TripForm
from .models import Destination

User = get_user_model()

class HomeView(LoginRequiredMixin, TemplateView):
    redirect_field_name = 'account:home'
    template_name = 'destinations/dashboard.html'

    def get_context_data(self, **kwargs):
        obj_list = super(HomeView, self).get_context_data(**kwargs)
        qs = Destination.objects.all()
        user_results = qs.filter(users_on_trip=self.request.user)
        others_trips = qs.exclude(users_on_trip=self.request.user)
        obj_list['user_trips'] = user_results
        obj_list['other_users_trips'] = others_trips
        return obj_list

    def post(self, request, *args, **kwargs):
        # You can handle post requests if needed
        return render(request, self.template_name)

class DestinationDetailSlugView(DetailView):
    template_name = "destinations/trip_detail.html"

    def get_object(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        try:
            instance = Destination.objects.get(slug=slug)
        except Destination.DoesNotExist:
            raise Http404("Not found..")
        except Destination.MultipleObjectsReturned:
            qs = Destination.objects.filter(slug=slug)
            instance = qs.first()
        except:
            raise Http404("Something broke ")
        return instance

class AddDestinationFormView(LoginRequiredMixin, TemplateView):
    redirect_field_name = 'account:home'
    form_class = TripForm
    initial = {'key': 'value'}
    template_name = 'destinations/trip_add.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            instance = Destination.objects.new(form, request.user)
            if instance:
                return redirect('travel:home')
            else:
                return render(request, self.template_name, {'form': form})
        return render(request, self.template_name, {'form': form})

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})


def UpdateDestinationView(request):
    destination_id = request.POST.get('destination_id')
    is_planner = request.POST.get('planner')
    user = request.user

    if is_planner:
        try:
            destination_obj = Destination.objects.get(id=destination_id)
        except Destination.DoesNotExist:
            messages.error(request, "Destination does not exist.")
            return redirect('travel:home')
        if destination_obj:
            destination_obj.delete()
        return redirect('travel:home')

    if destination_id is not None:
        try:
            destination_obj = Destination.objects.get(id=destination_id)
        except Destination.DoesNotExist:
            messages.error(request, "Destination does not exist.")
            return redirect('travel:home')
        if destination_obj:
            qs = destination_obj.users_on_trip.filter(id=user.id).exists()
            if qs:
                destination_obj.users_on_trip.remove(request.user.id)
                added = False
            else:
                destination_obj.users_on_trip.add(request.user.id)
                added = True

    if request.headers.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        json_data = {
            "added": added,
            "remove": not added,
        }
        return JsonResponse(json_data)

    return redirect('travel:home')

travelbuddy/destinations/templates/destinations/dashboard.html
{% extends 'base.html'%}
{% load static %}

{% block title %} | Dashboard {% endblock %}

{% block content %}

{% url 'account:login' as login_url %}

{% include 'partials/navbar.html' %}
<div class="container">

  <div class="user_trips" id="">
    {% if user_trips %}
    <h4 class="text-center">Your Scheduled Trips</h4>
      <table class="table table-hover table-dark text-center">
        <thead>
          <tr>
            
            <th scope="col">Destination</th>
            <th scope="col">From</th>
            <th scope="col">To</th>
            <th scope="col"  class="d-none d-lg-block">Plan</th>
            <th scope="col">Rating</th>
          </tr>
        </thead>
        <tbody>
          {% for location in user_trips %}
          <tr>
           
            <td><a href="{{ location.get_absolute_url }}">{{ location.location }}</a></td>
            <td>{{ location.start_date }}</td>
            <td>{{ location.end_date }}</td>
            <td class="d-none d-lg-block">{{ location.description }}</td>
            <td>{{ location.rating }}</td>
           <td> <th scope="row form-inline">
              <form class="form-destination-ajax" method="POST" action='{% url "travel:destination_update" %}'
                data-endpoint='{% url "travel:destination_update" %}'>
                {% csrf_token %}
                <input type="hidden" name="destination_id" value="{{ location.id }}" />
                <button class="btn btn-warning btn-sm" type="submit">Remove</button>
              </form>
              {% if location.planner.id == user.id %}<form class="form-destination-ajax pt-1" method="POST"
                action='{% url "travel:destination_update" %}' data-endpoint='{% url "travel:destination_update" %}'>
                {% csrf_token %}
                <input type="hidden" name="destination_id" value="{{ location.id }}" />
                <input type="hidden" name="planner" value="{{ True }}" />
                <button class="btn btn-danger btn-sm" type="submit">Delete</button>
              </form>
              {% endif %}
            </th></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
  </div>
  <h3 class="text-center pb-2">
    No Trips scheduled: <a class="btn btn-warning btn-sm" href='{% url "travel:add_trip" %}'> Add Plan</a>
  </h3>
  {% endif %}


  {% if other_users_trips %}
  <div class="others_trips">
    <h4 class="text-center pad">Other User's Travel Plans</h4>
    <div class="table-responsive-md">
      <table class="table table-hover table-dark text-center rounded-lg">
        <thead>
          <tr>
            <th scope="col" class="d-none d-lg-block">Name</th>
            <th scope="col">Destination</th>
            <th scope="col">From</th>
            <th scope="col">To</th>
            <th scope="col">Rating</th>
            <th scope="col">Want to Join?</th>
            
          </tr>
        </thead>
        <tbody>
          {% for trip in other_users_trips %}
          <tr>
            <td class="d-none d-lg-block">{{ trip.planner.first_name }}</td>
            <td><a href="{{ trip.get_absolute_url }}">{{ trip.location }}</a></td>
            <td>{{ trip.start_date }}</td>
            <td>{{ trip.end_date }}</td>
            <td>{{ trip.rating }}</td>
            <form class="form-destination-ajax" method="POST" action='{% url "travel:destination_update" %}'
              data-endpoint='{% url "travel:destination_update" %}'>
              {% csrf_token %}
              <input type="hidden" name="destination_id" value="{{ trip.id }}" />
              <td><button class="btn btn-info" type="submit">Join</button></td>
            </form>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  {% else %}
  <h3 class="text-center pt-2">
    No other trips are scheduled
  </h3>
</div>
{% endif %}

{% endblock %}

travelbuddy/destinations/templates/destinations/trip_detail.html
{% extends 'base.html'%}
{% load static %}

{% block title %} | Dashboard {% endblock %}

{% block content %}

{% url 'home' as home_url %}
{% url 'account:login' as login_url %}
{% url 'travel:home' as home_url %}
{% url 'logout' as logout_url %}
{% url 'travel:add_trip' as add_trip_url %}


{% include 'partials/navbar.html' %}
<div class="container">

  <div class="row">

    <div class="col-md-6">
      <div class="this_destination">
        <h2>Destination: {{ destination.location }}</h2>
        <hr>
        <h5>Planned By: {{ destination.planner.first_name }} {{ destination.planner.last_name }}</h5>
        <h5>Plan: {{ destination.description }}</h5>
        <h5>From: {{ destination.start_date }}</h5>
        <h5>To: {{ destination.end_date }}</h5>
        <h5>Rating: {{ destination.rating}}</h5>
      </div>
    </div>

    <div class="col-md-6">
      <div class="others_this_destination">
        <h2>Accompaning Travelers:</h2>
        <hr>
        {% for user in destination.users_on_trip.all %}
        <h5>{{ user.first_name }} {{ user.last_name }}</h5>
        {% endfor %}
      </div>
    </div>
  </div>


</div>
{% endblock %}